// src/features/menu/menu-data.ts
import type { MenuItem } from "./menuTypes";
import { coffeeImages /*foodImages*/ } from "./menuImages";
import { Coffee } from "lucide-react";

export const menuItems: MenuItem[] = [
  // ============= Coffee Items =================
  {
    id: 1,
    name: "Chill Vietnamese",
    description: "Rich espresso with perfectly steamed milk and artistic foam",
    price: "$4.50",
    image: coffeeImages.chillVietnamese,
    category: "Cold Coffee",
    rating: 4.9,
    time: "3 mins",
    tags: ["Popular", "Signature"],
    fit: "Contain",
  },
  {
    id: 2,
    name: "Affogato",
    description: `A traditional Italian dessert of vanilla gelato "drowned" in a shot of hot espresso`,
    price: "$3.75",
    image: coffeeImages.affogato,
    category: "Cold Coffee",
    rating: 4.9,
    time: "1 min",
    tags: ["Refreshing", "Strong"],
    fit: "Contain",
  },
  {
    id: 3,
    name: "Cappuccino Classic",
    description:
      "Traditional Italian cappuccino with perfect foam to espresso ratio",
    price: "$4.00",
    image: coffeeImages.classicCappuccino,
    category: "Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Classic", "Traditional"],
    fit: "Contain",
  },
  {
    id: 4,
    name: "Chilled Brew",
    description:
      "Rich espresso shots diluted with cold water. A perfectly crisp and refreshing cool-down.",
    price: "$4.00",
    image: coffeeImages.icedAmericano,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Refreshing", "Chilled"],
    fit: "Contain",
  },
  {
    id: 5,
    name: "Italian Kick",
    description:
      "A bold, concentrated shot of tradition for an instant, powerful jolt of energy.",
    price: "$4.00",
    image: coffeeImages.italianKick,
    category: "Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Refreshing", "Strong"],
    fit: "Contain",
  },
  {
    id: 6,
    name: "Classic Chill",
    description:
      "A rich, icy, and perfectly blended coffee beverage, crafted for sweet, creamy refreshment.",
    price: "$4.00",
    image: coffeeImages.classicChill,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
  },
  {
    id: 7,
    name: "Cocoa Dream",
    description:
      "A true Cocoa Dream deep, velvety, and exquisitely satisfying.",
    price: "$4.00",
    image: coffeeImages.cocoaDream,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
  },
  {
    id: 8,
    name: "Cocoa Breeze",
    description:
      "The ultimate chocolate and coffee comfort: a cozy, creamy hug in a cup.",
    price: "$4.00",
    image: coffeeImages.cocoaBreeze,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
  },
  {
    id: 9,
    name: "Velvet Chill",
    description:
      "Espresso and fresh cold milk over ice. The essential, smooth, and cool refreshment.",
    price: "$4.00",
    image: coffeeImages.velvetChill,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
  },
  {
    id: 10,
    name: "Flavoured Iced Latte",
    description:
      "Smooth, creamy iced perfection. Personalize your sip: Vanilla, Caramel, Irish, or Hazelnut.",
    price: "$4.00",
    image: coffeeImages.flavouredIcedLatte,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
  },
  {
    id: 11,
    name: "Silken Roast",
    description:
      "The elegant simplicity of espresso and steamed milk. Perfectly smooth, warm, and comforting.",
    price: "$4.00",
    image: coffeeImages.silkenRoast,
    category: "Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Smooth", "Warm"],
    fit: "Contain",
  },
  {
    id: 12,
    name: "Saigon Brew",
    description:
      "Intense, rich dark coffee brewed in traditional style. Perfect balance of sweetness & creamy comfort.",
    price: "$4.00",
    image: coffeeImages.saigonBrew,
    category: "Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Smooth", "Warm"],
    fit: "Contain",
  },
  {
    id: 13,
    name: "Whiskey Roasted",
    description:
      "The bold kick of Irish whiskey and coffee. Intensely warm, served black (no cream).",
    price: "$4.00",
    image: coffeeImages.whiskeyRoasted,
    category: "Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Whiskey", "Warm"],
    fit: "Contain",
  },
  {
    id: 14,
    name: "Americano",
    description:
      "Rich espresso shots extended with hot water. A bold, clean, and classic coffee preparation.",
    price: "$4.00",
    image: coffeeImages.americano,
    category: "Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Classic", "Warm"],
    fit: "Contain",
  },
  {
    id: 15,
    name: "Choco Bliss",
    description:
      "The perfect mix of espresso and melted chocolate. A rich, creamy, and decadent warm sip.",
    price: "$4.00",
    image: coffeeImages.chocoBliss,
    category: "Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Warm"],
    fit: "Contain",
  },
  {
    id: 16,
    name: "Coke Espresso",
    description:
      "A bold shot poured into chilled Coke. Maximum caffeine, maximum fizz.",
    price: "$4.00",
    image: coffeeImages.cokeEspresso,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fizzy", "Icy"],
    fit: "Contain",
  },
  {
    id: 17,
    name: "RedBull Espresso",
    description:
      "A bold shot poured into chilled Red Bull. Maximum caffeine, maximum fizz.",
    price: "$4.00",
    image: coffeeImages.redBullEspresso,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fizzy", "Icy"],
    fit: "Contain",
  },
  {
    id: 18,
    name: "Ginger Ale",
    description:
      "A bold shot of coffee layered over bubbly ginger ale. Spicy, sweet, and intensely refreshing.",
    price: "$4.00",
    image: coffeeImages.gingerAle,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fizzy", "Icy"],
    fit: "Contain",
  },
  {
    id: 19,
    name: "Orange Sunrise",
    description:
      "A vibrant, layered blend capturing the hues of dawn. A beautiful start to your day.",
    price: "$4.00",
    image: coffeeImages.orangeSunrise,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Cintrus", "Icy"],
    fit: "Contain",
  },

  //   ================= Tea Items =================
  {
    id: 20,
    name: "Masala Tea",
    description:
      "Creamy tea infused with rich, warming Masala spices. Sweet, fragrant, and perfectly comforting.",
    price: "$4.00",
    image: coffeeImages.masalaTea,
    category: "Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Warm"],
    fit: "Contain",
  },
  {
    id: 21,
    name: "Blueberry Iced Tea",
    description:
      "Sweet blueberry meets crisp iced tea. Vibrant, fruity, and intensely refreshing.",
    price: "$4.00",
    image: coffeeImages.blueBerryIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fruity", "Icy"],
    fit: "Contain",
  },
  {
    id: 22,
    name: "Lemon Tea",
    description:
      "Classic tea infused with fresh, zesty lemon. A perfect balance of warmth and bright, clean flavor.",
    price: "$4.00",
    image: coffeeImages.lemonTea,
    category: "Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Zesty", "warm"],
    fit: "Contain",
  },
  {
    id: 23,
    name: "Litchi Iced Tea",
    description:
      "Chilled tea kissed with the sweet, fragrant taste of litchi. Perfectly refreshing summer delight.",
    price: "$4.00",
    image: coffeeImages.litchiIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Delightful", "Icy"],
    fit: "Contain",
  },
  {
    id: 23,
    name: "Black Tea",
    description:
      "The traditional, rich essence of fully oxidized tea leaves. A bold and perfectly warm cup of clarity.",
    price: "$4.00",
    image: coffeeImages.blackTea,
    category: "Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
  },
  {
    id: 24,
    name: "Saffron Kahwa",
    description:
      "Kashmiri saffron and green tea. A golden, aromatic, and intensely soothing infusion.",
    price: "$4.00",
    image: coffeeImages.saffronKahwa,
    category: "Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
  },
  {
    id: 25,
    name: "Lemon Ginger Tea",
    description: "The fiery warmth of ginger meets bright, sharp lemon zest.",
    price: "$4.00",
    image: coffeeImages.lemonGingerTea,
    category: "Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Zesty", "Warm"],
    fit: "Contain",
  },
  {
    id: 26,
    name: "Grenadine Iced Tea",
    description:
      "Iced tea with a sweet ruby splash of grenadine. Vibrant, fruity, and instantly refreshing.",
    price: "$4.00",
    image: coffeeImages.grenadineIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Grenadine", "Icy"],
    fit: "Contain",
  },
  {
    id: 27,
    name: "Lemon Iced Tea",
    description:
      "The classic pairing of cool tea and sharp, zesty lemon. Perfectly simple, thirst-quenching, and utterly crisp.",
    price: "$4.00",
    image: coffeeImages.lemonIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Zesty", "Icy"],
    fit: "Contain",
  },

  // ============= Shakes =================
  {
    id: 28,
    name: "Berry Burst",
    description:
      "Indulgent sweetness blended with a burst of sweet blueberries. A thick, frosty, and utterly creamy.",
    price: "$4.00",
    image: coffeeImages.berryBurst,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 29,
    name: "Tropical Chill",
    description:
      "Creamy base meets tangy tropical pineapple. A frosty, sweet, island indulgence.",
    price: "$4.00",
    image: coffeeImages.tropicalChill,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 30,
    name: "Blushing Berry",
    description:
      "Thick, velvety blend of ice cream and strawberries. A perfectly sweet, fruity, and nostalgic treat.",
    price: "$4.00",
    image: coffeeImages.blushingBerry,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 31,
    name: "Tropical Sunshine",
    description:
      "The essence of tropical summer blended thick and smooth. Rich mango flavor in a creamy shake.",
    price: "$4.00",
    image: coffeeImages.tropicalSunshine,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 32,
    name: "Crunchy Choco Delight (KitKat)",
    description:
      "Chocolate shake with real Kit Kat pieces. Creamy indulgence with a crunchy wafer break.",
    price: "$4.00",
    image: coffeeImages.crunchyChocoDelight,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 33,
    name: "Cookie Crumble (Oreo)",
    description:
      "The ultimate cookies-and-cream. A thick, cold shake with chunks of crunchy chocolate wafer.",
    price: "$4.00",
    image: coffeeImages.cookieCrumble,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 34,
    name: "Golden Nut Bliss (Ferrero)",
    description:
      "Velvety chocolate and hazelnut blend. A rich, cold treat with a satisfying nutty crunch.",
    price: "$4.00",
    image: coffeeImages.goldenNutBliss,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 35,
    name: "Spiced Biscuit Bliss (Biscoff)",
    description:
      "Creamy shake with caramelized Biscoff spice. Thick, frosty, and loaded with cookie crunch.",
    price: "$4.00",
    image: coffeeImages.spicedBiscuitBliss,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 36,
    name: "Choco Island Freak Shake",
    description:
      "Chocolate overload and dripping with sprinkles. The thick, dark shake with an Oreo and Kit Kat.",
    price: "$4.00",
    image: coffeeImages.chocoIslandFreakShake,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 37,
    name: "Brownie Shake",
    description:
      "Decadent chocolate meets fudgy brownie chunks. A rich, frosty shake with a satisfying chew.",
    price: "$4.00",
    image: coffeeImages.brownieShake,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
];
