// src/features/menu/menu-data.ts
import type { MenuItem } from "./menuTypes";
import { coffeeImages /*foodImages*/ } from "./menuImages";

export const menuItems: MenuItem[] = [
  // ============= Coffee Items =================
  {
    id: 1,
    name: "Chill Vietnamese",
    description: "Rich espresso with perfectly steamed milk and artistic foam",
    price: "219",
    image: coffeeImages.chillVietnamese,
    category: "Speciality Coffee",
    rating: 4.9,
    time: "3 mins",
    tags: ["Popular", "Signature"],
    fit: "Contain",
  },
  {
    id: 2,
    name: "Sweet Shot",
    description: `A traditional Italian dessert of vanilla gelato "drowned" in a shot of hot espresso`,
    price: "₹179",
    image: coffeeImages.affogato,
    category: "Hot Coffee",
    rating: 4.9,
    time: "1 min",
    tags: ["Refreshing", "Strong"],
    fit: "Contain",
    variants: [],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 3,
    name: "Velvet Brew",
    description:
      "Traditional Italian cappuccino with perfect foam to espresso ratio",
    price: "₹169",
    image: coffeeImages.classicCappuccino,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Classic", "Traditional"],
    fit: "Contain",
    variants: [
      { name: "Choclate", price: "₹209" },
      { name: "Hazelnut", price: "₹209" },
      { name: "Irish", price: "₹209" },
      { name: "Caramel", price: "₹209" },
      { name: "Rose Petal", price: "₹209" },
    ],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 4,
    name: "Chilled Brew",
    description:
      "Rich espresso shots diluted with cold water. A perfectly crisp and refreshing cool-down.",
    price: "179",
    image: coffeeImages.icedAmericano,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Refreshing", "Chilled"],
    fit: "Contain",
  },
  {
    id: 5,
    name: "Italian Kick",
    description:
      "A bold, concentrated shot of tradition for an instant, powerful jolt of energy.",
    price: "₹129",
    image: coffeeImages.italianKick,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Refreshing", "Strong"],
    fit: "Contain",
    variants: [],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 6,
    name: "Classic Chill",
    description:
      "A rich, icy, and perfectly blended coffee beverage, crafted for sweet, creamy refreshment.",
    price: "₹169",
    image: coffeeImages.classicChill,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
    variants: [
      { name: "Caramel", price: "₹219" },
      { name: "Irish", price: "₹219" },
      { name: "Hazelnut", price: "₹219" },
      { name: "Vanilla", price: "₹219" },
      { name: "Brownie", price: "₹219" },
      { name: "Tiramisu Cloud", price: "₹219" },
    ],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 7,
    name: "Cocoa Dream",
    description:
      "A true Cocoa Dream deep, velvety, and exquisitely satisfying.",
    price: "199",
    image: coffeeImages.cocoaDream,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
  },
  {
    id: 8,
    name: "Cocoa Breeze",
    description:
      "The ultimate chocolate and coffee comfort: a cozy, creamy hug in a cup.",
    price: "₹199",
    image: coffeeImages.cocoaBreeze,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
    variants: [
      { name: "Caramel", price: "₹219" },
      { name: "Irish", price: "₹219" },
      { name: "Hazelnut", price: "₹219" },
      { name: "Vanilla", price: "₹219" },
      { name: "Brownie", price: "₹219" },
      { name: "Tiramisu Cloud", price: "₹219" },
    ],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 9,
    name: "Velvet Chill",
    description:
      "Espresso and fresh cold milk over ice. The essential, smooth, and cool refreshment.",
    price: "229",
    image: coffeeImages.velvetChill,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
  },
  {
    id: 10,
    name: "Flavoured Iced Latte",
    description:
      "Smooth, creamy iced perfection. Personalize your sip: Vanilla, Caramel, Irish, or Hazelnut.",
    price: "229",
    image: coffeeImages.flavouredIcedLatte,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
    variants: [
      { name: "Vanilla", price: "229" },
      { name: "Caramel", price: "229" },
      { name: "Irish", price: "229" },
      { name: "Hazelnut", price: "229" },
    ],
  },
  {
    id: 11,
    name: "Silken Roast",
    description:
      "The elegant simplicity of espresso and steamed milk. Perfectly smooth, warm, and comforting.",
    price: "₹179",
    image: coffeeImages.silkenRoast,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Smooth", "Warm"],
    fit: "Contain",
    variants: [
      { name: "Caramel", price: "₹229" },
      { name: "Irish", price: "₹229" },
      { name: "Hazelnut", price: "₹229" },
    ],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 12,
    name: "Saigon Brew",
    description:
      "Intense, rich dark coffee brewed in traditional style. Perfect balance of sweetness & creamy comfort.",
    price: "₹209",
    image: coffeeImages.saigonBrew,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Smooth", "Warm"],
    fit: "Contain",
    variants: [],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 13,
    name: "Whiskey Roast",
    description:
      "The bold kick of Irish whiskey and coffee. Intensely warm, served black (no cream).",
    price: "219",
    image: coffeeImages.whiskeyRoasted,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Whiskey", "Warm"],
    fit: "Contain",
  },
  {
    id: 14,
    name: "Americano",
    description:
      "Rich espresso shots extended with hot water. A bold, clean, and classic coffee preparation.",
    price: "₹169",
    image: coffeeImages.americano,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Classic", "Warm"],
    fit: "Contain",
    variants: [],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 15,
    name: "Choco Bliss",
    description:
      "The perfect mix of espresso and melted chocolate. A rich, creamy, and decadent warm sip.",
    price: "₹229",
    image: coffeeImages.chocoBliss,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Warm"],
    fit: "Contain",
    variants: [
      { name: "Hazelnut", price: "₹249" },
      { name: "Irish", price: "₹249" },
      { name: "Caramel", price: "₹249" },
    ],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 16,
    name: "Coke Espresso",
    description:
      "A bold shot poured into chilled Coke. Maximum caffeine, maximum fizz.",
    price: "239",
    image: coffeeImages.cokeEspresso,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fizzy", "Icy"],
    fit: "Contain",
  },
  {
    id: 17,
    name: "Red Bull Espresso",
    description:
      "A bold shot poured into chilled Red Bull. Maximum caffeine, maximum fizz.",
    price: "249",
    image: coffeeImages.redBullEspresso,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fizzy", "Icy"],
    fit: "Contain",
  },
  {
    id: 18,
    name: "Ginger Ale",
    description:
      "A bold shot of coffee layered over bubbly ginger ale. Spicy, sweet, and intensely refreshing.",
    price: "239",
    image: coffeeImages.gingerAle,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fizzy", "Icy"],
    fit: "Contain",
  },
  {
    id: 19,
    name: "Orange Sunrise",
    description:
      "A vibrant, layered blend capturing the hues of dawn. A beautiful start to your day.",
    price: "239",
    image: coffeeImages.orangeSunrise,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Cintrus", "Icy"],
    fit: "Contain",
  },

  //   ================= Tea Items =================
  {
    id: 20,
    name: "Masala Tea",
    description:
      "Creamy tea infused with rich, warming Masala spices. Sweet, fragrant, and perfectly comforting.",
    price: "169",
    image: coffeeImages.masalaTea,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Warm"],
    fit: "Contain",
  },
  {
    id: 21,
    name: "Peach Ice Tea",
    description:
      "Sweet blueberry meets crisp iced tea. Vibrant, fruity, and intensely refreshing.",
    price: "169",
    image: coffeeImages.blueBerryIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fruity", "Icy"],
    fit: "Contain",
  },
  {
    id: 22,
    name: "Lemon Tea",
    description:
      "Classic tea infused with fresh, zesty lemon. A perfect balance of warmth and bright, clean flavor.",
    price: "169",
    image: coffeeImages.lemonTea,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Zesty", "warm"],
    fit: "Contain",
  },
  {
    id: 23,
    name: "Litchi Ice Tea",
    description:
      "Chilled tea kissed with the sweet, fragrant taste of litchi. Perfectly refreshing summer delight.",
    price: "169",
    image: coffeeImages.litchiIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Delightful", "Icy"],
    fit: "Contain",
  },
  {
    id: 23,
    name: "Black Tea",
    description:
      "The traditional, rich essence of fully oxidized tea leaves. A bold and perfectly warm cup of clarity.",
    price: "169",
    image: coffeeImages.blackTea,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
  },
  {
    id: 24,
    name: "Saffron Kahwa",
    description:
      "Kashmiri saffron and green tea. A golden, aromatic, and intensely soothing infusion.",
    price: "189",
    image: coffeeImages.saffronKahwa,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
    variants: [
      { name: "Lavender White Tea", price: "₹189" },
      { name: "Rose White Tea", price: "₹189" },
      { name: "Caramel Dessert Tea", price: "₹189" },
    ],
  },
  {
    id: 25,
    name: "Ginger Lemon Tea",
    description: "The fiery warmth of ginger meets bright, sharp lemon zest.",
    price: "169",
    image: coffeeImages.lemonGingerTea,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Zesty", "Warm"],
    fit: "Contain",
  },
  {
    id: 26,
    name: "Blueberry Ice Tea",
    description:
      "Iced tea with a sweet ruby splash of grenadine. Vibrant, fruity, and instantly refreshing.",
    price: "169",
    image: coffeeImages.grenadineIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Blueberry", "Icy"],
    fit: "Contain",
  },
  {
    id: 27,
    name: "Lemon Ice Tea",
    description:
      "The classic pairing of cool tea and sharp, zesty lemon. Perfectly simple and thirst-quenching.",
    price: "169",
    image: coffeeImages.lemonIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Zesty", "Icy"],
    fit: "Contain",
  },

  // ============= Shakes =================
  {
    id: 28,
    name: "Berry Burst",
    description:
      "Indulgent sweetness blended with a burst of sweet blueberries. A thick, frosty, and utterly creamy.",
    price: "199",
    image: coffeeImages.berryBurst,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 29,
    name: "Tropical Chill",
    description:
      "Creamy base meets tangy tropical pineapple. A frosty, sweet, island indulgence.",
    price: "199",
    image: coffeeImages.tropicalChill,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 30,
    name: "Blushing Berry",
    description:
      "Thick, velvety blend of ice cream and strawberries. A perfectly sweet, fruity, and nostalgic treat.",
    price: "199",
    image: coffeeImages.blushingBerry,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 31,
    name: "Tropical Sunshine",
    description:
      "The essence of tropical summer blended thick and smooth. Rich mango flavor in a creamy shake.",
    price: "199",
    image: coffeeImages.tropicalSunshine,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 32,
    name: "Crunchy Choco Delight (KitKat)",
    description:
      "Chocolate shake with real Kit Kat pieces. Creamy indulgence with a crunchy wafer break.",
    price: "229",
    image: coffeeImages.crunchyChocoDelight,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 33,
    name: "Cookie Crumble (Oreo)",
    description:
      "The ultimate cookies-and-cream. A thick, cold shake with chunks of crunchy chocolate wafer.",
    price: "229",
    image: coffeeImages.cookieCrumble,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 34,
    name: "Golden Nut Bliss (Ferrero)",
    description:
      "Velvety chocolate and hazelnut blend. A rich, cold treat with a satisfying nutty crunch.",
    price: "229",
    image: coffeeImages.goldenNutBliss,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 35,
    name: "Spiced Biscuit Bliss (Biscoff)",
    description:
      "Creamy shake with caramelized Biscoff spice. Thick, frosty, and loaded with cookie crunch.",
    price: "279",
    image: coffeeImages.spicedBiscuitBliss,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 36,
    name: "Choco Island Freak Shake",
    description:
      "Chocolate overload and dripping with sprinkles. The thick, dark shake with an Oreo and Kit Kat.",
    price: "249",
    image: coffeeImages.chocoIslandFreakShake,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 37,
    name: "Brownie Shake",
    description:
      "Decadent chocolate meets fudgy brownie chunks. A rich, frosty shake with a satisfying chew.",
    price: "229",
    image: coffeeImages.brownieShake,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },

  // ============= Mojitos =================
  {
    id: 38,
    name: "Blueberry Mojito",
    description:
      "Crisp mint and zesty lime meet sweet, plump blueberries. Intensely cool and bubbly.",
    price: "$4.00",
    image: coffeeImages.blueberry,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Minty", "Icy"],
    fit: "Contain",
  },
  {
    id: 39,
    name: "Cool Blue Mojito",
    description:
      "The classic mint and lime, electrified blue. Intensely cool, crisp, and ultra-bubbly.",
    price: "$4.00",
    image: coffeeImages.coolBlue,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Minty", "Icy"],
    fit: "Contain",
  },
  {
    id: 40,
    name: "Green Apple Mojito",
    description:
      "Mint and lime with a tart green apple kick. Crisp, cool, and utterly fizzy refreshment.",
    price: "$4.00",
    image: coffeeImages.greenApple,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 41,
    name: "Grenadine Mojito",
    description:
      "Classic zest and mint with a sweet grenadine burst. Perfectly cool, vibrant, and ultra-bubbly.",
    price: "$4.00",
    image: coffeeImages.grenadine,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 42,
    name: "Litchi Mojito",
    description:
      "Mint and lime with sweet, exotic litchi. Fragrant, cool, and perfectly bubbly.",
    price: "$4.00",
    image: coffeeImages.litchi,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 43,
    name: "Watermelon Mojito",
    description:
      "Invigorating mint and lime with a sweet watermelon burst. Perfectly cool, and refreshing.",
    price: "$4.00",
    image: coffeeImages.watermelon,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },

  // ============= Desserts =================
  {
    id: 44,
    name: "Biscoff Cheesecake",
    description:
      "Creamy base and irresistible caramelized Biscoff. A rich, velvety treat with a crunchy cookie crust.",
    price: "$4.00",
    image: coffeeImages.biscoffCake,
    category: "Desserts",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Crunchy"],
    fit: "Contain",
  },
  {
    id: 45,
    name: "Blueberry Cheesecake",
    description:
      "Velvety cream cheese and a buttery crust. Crowned with a burst of sweet, tart blueberries.",
    price: "$4.00",
    image: coffeeImages.blueberryCake,
    category: "Desserts",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Velvety"],
    fit: "Contain",
  },
  {
    id: 46,
    name: "Brownie",
    description:
      "Deep, dark chocolate baked to fudgy perfection. A rich, chewy, and utterly irresistible classic.",
    price: "$4.00",
    image: coffeeImages.brownie,
    category: "Desserts",
    rating: 4.8,
    time: "3 mins",
    tags: ["Chocolaty", "Fudgy"],
    fit: "Contain",
  },
  {
    id: 47,
    name: "New York Cheesecake",
    description:
      "The dense, ultra-rich classic set on a graham crust. Velvety smooth.",
    price: "$4.00",
    image: coffeeImages.newYorkCheesecake,
    category: "Desserts",
    rating: 4.9,
    time: "3 mins",
    tags: ["Smooth", "Velvety"],
    fit: "Contain",
  },
  {
    id: 48,
    name: "Sizzling",
    description:
      "The ultimate chocolate experience, sizzling. Fudgy brownie topped with melting ice cream and sauce.",
    price: "$4.00",
    image: coffeeImages.sizzling,
    category: "Desserts",
    rating: 4.9,
    time: "3 mins",
    tags: ["Smooth", "Velvety"],
    fit: "Contain",
  },
  {
    id: 49,
    name: "Green Tea",
    description:
      "Light and calming with antioxidants. It offers a calm, refreshing experience.",
    price: "169",
    image: coffeeImages.greenTea,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
  },
  {
    id: 50,
    name: "Hot Chocolate",
    description:
      "Light and calming with antioxidants. It offers a calm, refreshing experience.",
    price: "169",
    image: coffeeImages.hotChocolate,
    category: "Hot Chocolate",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
    variants: [
      { name: "Cocoa", price: "₹189" },
      { name: "Hazelnut", price: "₹209" },
      { name: "Caramel", price: "₹209" },
      { name: "Strawberry", price: "₹209" },
    ],
  },
  {
    id: 51,
    name: "French Velvet",
    description:
      "Light and calming with antioxidants. It offers a calm, refreshing experience.",
    price: "219",
    image: coffeeImages.frenchVelvet,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
  },
  {
    id: 52,
    name: "Tonic Water",
    description:
      "Light and calming with antioxidants. It offers a calm, refreshing experience.",
    price: "239",
    image: coffeeImages.tonicWaterEspresso,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
  },
];
