// src/features/menu/menu-data.ts
import { coffeeImages /*foodImages*/, foodImages } from "./menuImages";
import type { MenuItem } from "./menuTypes";

export const menuItems: MenuItem[] = [
  // ============= Coffee Items =================
  {
    id: 1,
    name: "Chill Vietnamese",
    description: "Rich espresso with perfectly steamed milk and artistic foam",
    price: "219",
    image: coffeeImages.chillVietnamese,
    category: "Speciality Coffee",
    rating: 4.9,
    time: "3 mins",
    tags: ["Popular", "Signature"],
    fit: "Contain",
  },
  {
    id: 2,
    name: "Sweet Shot",
    description: `A traditional Italian dessert of vanilla gelato "drowned" in a shot of hot espresso`,
    price: "₹179",
    image: coffeeImages.affogato,
    category: "Hot Coffee",
    rating: 4.9,
    time: "1 min",
    tags: ["Refreshing", "Strong"],
    fit: "Contain",
    variants: [],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 3,
    name: "Velvet Brew",
    description: "Traditional Italian cappuccino with perfect foam to espresso ratio",
    price: "₹169",
    image: coffeeImages.classicCappuccino,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Classic", "Traditional"],
    fit: "Contain",
    variants: [
      { name: "Choclate", price: "₹209" },
      { name: "Hazelnut", price: "₹209" },
      { name: "Irish", price: "₹209" },
      { name: "Caramel", price: "₹209" },
      { name: "Rose Petal", price: "₹209" },
    ],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 4,
    name: "Chilled Brew",
    description: "Rich espresso shots diluted with cold water. A perfectly crisp and refreshing cool-down.",
    price: "179",
    image: coffeeImages.icedAmericano,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Refreshing", "Chilled"],
    fit: "Contain",
  },
  {
    id: 5,
    name: "Italian Kick",
    description: "A bold, concentrated shot of tradition for an instant, powerful jolt of energy.",
    price: "₹129",
    image: coffeeImages.italianKick,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Refreshing", "Strong"],
    fit: "Contain",
    variants: [],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 6,
    name: "Classic Chill",
    description: "A rich, icy, and perfectly blended coffee beverage, crafted for sweet, creamy refreshment.",
    price: "₹169",
    image: coffeeImages.classicChill,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
    variants: [
      { name: "Caramel", price: "₹219" },
      { name: "Irish", price: "₹219" },
      { name: "Hazelnut", price: "₹219" },
      { name: "Vanilla", price: "₹219" },
      { name: "Brownie", price: "₹219" },
      { name: "Tiramisu Cloud", price: "₹219" },
    ],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 7,
    name: "Cocoa Dream",
    description: "A true Cocoa Dream deep, velvety, and exquisitely satisfying.",
    price: "199",
    image: coffeeImages.cocoaDream,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
  },
  {
    id: 8,
    name: "Cocoa Breeze",
    description: "The ultimate chocolate and coffee comfort: a cozy, creamy hug in a cup.",
    price: "₹199",
    image: coffeeImages.cocoaBreeze,
    category: "Cold Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
    variants: [
      { name: "Caramel", price: "₹219" },
      { name: "Irish", price: "₹219" },
      { name: "Hazelnut", price: "₹219" },
      { name: "Vanilla", price: "₹219" },
      { name: "Brownie", price: "₹219" },
      { name: "Tiramisu Cloud", price: "₹219" },
    ],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 9,
    name: "Velvet Chill",
    description: "Espresso and fresh cold milk over ice. The essential, smooth, and cool refreshment.",
    price: "229",
    image: coffeeImages.velvetChill,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
  },
  {
    id: 10,
    name: "Flavoured Iced Latte",
    description:
      "Smooth, creamy iced perfection. Personalize your sip: Vanilla, Caramel, Irish, or Hazelnut.",
    price: "229",
    image: coffeeImages.flavouredIcedLatte,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Icy"],
    fit: "Contain",
    variants: [
      { name: "Vanilla", price: "229" },
      { name: "Caramel", price: "229" },
      { name: "Irish", price: "229" },
      { name: "Hazelnut", price: "229" },
    ],
  },
  {
    id: 11,
    name: "Silken Roast",
    description:
      "The elegant simplicity of espresso and steamed milk. Perfectly smooth, warm, and comforting.",
    price: "₹179",
    image: coffeeImages.silkenRoast,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Smooth", "Warm"],
    fit: "Contain",
    variants: [
      { name: "Caramel", price: "₹229" },
      { name: "Irish", price: "₹229" },
      { name: "Hazelnut", price: "₹229" },
    ],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 12,
    name: "Saigon Brew",
    description:
      "Intense, rich dark coffee brewed in traditional style. Perfect balance of sweetness & creamy comfort.",
    price: "₹209",
    image: coffeeImages.saigonBrew,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Smooth", "Warm"],
    fit: "Contain",
    variants: [],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 13,
    name: "Whiskey Roast",
    description: "The bold kick of Irish whiskey and coffee. Intensely warm, served black (no cream).",
    price: "219",
    image: coffeeImages.whiskeyRoasted,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Whiskey", "Warm"],
    fit: "Contain",
  },
  {
    id: 14,
    name: "Americano",
    description:
      "Rich espresso shots extended with hot water. A bold, clean, and classic coffee preparation.",
    price: "₹169",
    image: coffeeImages.americano,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Classic", "Warm"],
    fit: "Contain",
    variants: [],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 15,
    name: "Choco Bliss",
    description: "The perfect mix of espresso and melted chocolate. A rich, creamy, and decadent warm sip.",
    price: "₹229",
    image: coffeeImages.chocoBliss,
    category: "Hot Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Warm"],
    fit: "Contain",
    variants: [
      { name: "Hazelnut", price: "₹249" },
      { name: "Irish", price: "₹249" },
      { name: "Caramel", price: "₹249" },
    ],
    addOns: [{ name: "Extra Espresso Shot", price: "₹30" }],
  },
  {
    id: 16,
    name: "Coke Espresso",
    description: "A bold shot poured into chilled Coke. Maximum caffeine, maximum fizz.",
    price: "239",
    image: coffeeImages.cokeEspresso,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fizzy", "Icy"],
    fit: "Contain",
  },
  {
    id: 17,
    name: "Red Bull Espresso",
    description: "A bold shot poured into chilled Red Bull. Maximum caffeine, maximum fizz.",
    price: "249",
    image: coffeeImages.redBullEspresso,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fizzy", "Icy"],
    fit: "Contain",
  },
  {
    id: 18,
    name: "Ginger Ale",
    description:
      "A bold shot of coffee layered over bubbly ginger ale. Spicy, sweet, and intensely refreshing.",
    price: "239",
    image: coffeeImages.gingerAle,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fizzy", "Icy"],
    fit: "Contain",
  },
  {
    id: 19,
    name: "Orange Sunrise",
    description: "A vibrant, layered blend capturing the hues of dawn. A beautiful start to your day.",
    price: "239",
    image: coffeeImages.orangeSunrise,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Cintrus", "Icy"],
    fit: "Contain",
  },

  //   ================= Tea Items =================
  {
    id: 20,
    name: "Masala Tea",
    description:
      "Creamy tea infused with rich, warming Masala spices. Sweet, fragrant, and perfectly comforting.",
    price: "169",
    image: coffeeImages.masalaTea,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Warm"],
    fit: "Contain",
  },
  {
    id: 21,
    name: "Peach Ice Tea",
    description: "Sweet blueberry meets crisp iced tea. Vibrant, fruity, and intensely refreshing.",
    price: "169",
    image: coffeeImages.peachIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Fruity", "Icy"],
    fit: "Contain",
  },
  {
    id: 22,
    name: "Lemon Tea",
    description:
      "Classic tea infused with fresh, zesty lemon. A perfect balance of warmth and bright, clean flavor.",
    price: "169",
    image: coffeeImages.lemonTea,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Zesty", "warm"],
    fit: "Contain",
  },
  {
    id: 23,
    name: "Litchi Ice Tea",
    description:
      "Chilled tea kissed with the sweet, fragrant taste of litchi. Perfectly refreshing summer delight.",
    price: "169",
    image: coffeeImages.litchiIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Delightful", "Icy"],
    fit: "Contain",
  },
  {
    id: 23,
    name: "Black Tea",
    description:
      "The traditional, rich essence of fully oxidized tea leaves. A bold and perfectly warm cup of clarity.",
    price: "169",
    image: coffeeImages.blackTea,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
  },
  {
    id: 24,
    name: "Saffron Kahwa",
    description: "Kashmiri saffron and green tea. A golden, aromatic, and intensely soothing infusion.",
    price: "189",
    image: coffeeImages.saffronKahwa,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
    variants: [
      { name: "Lavender White Tea", price: "₹189" },
      { name: "Rose White Tea", price: "₹189" },
      { name: "Caramel Dessert Tea", price: "₹189" },
    ],
  },
  {
    id: 25,
    name: "Ginger Lemon Tea",
    description: "The fiery warmth of ginger meets bright, sharp lemon zest.",
    price: "169",
    image: coffeeImages.lemonGingerTea,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Zesty", "Warm"],
    fit: "Contain",
  },
  {
    id: 26,
    name: "Blueberry Ice Tea",
    description: "Iced tea with a sweet ruby splash of grenadine. Vibrant, fruity, and instantly refreshing.",
    price: "169",
    image: coffeeImages.blueberryIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Blueberry", "Icy"],
    fit: "Contain",
  },
  {
    id: 27,
    name: "Lemon Ice Tea",
    description:
      "The classic pairing of cool tea and sharp, zesty lemon. Perfectly simple and thirst-quenching.",
    price: "169",
    image: coffeeImages.lemonIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Zesty", "Icy"],
    fit: "Contain",
  },

  // ============= Shakes =================
  {
    id: 28,
    name: "Berry Burst",
    description:
      "Indulgent sweetness blended with a burst of sweet blueberries. A thick, frosty, and utterly creamy.",
    price: "199",
    image: coffeeImages.berryBurst,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 29,
    name: "Tropical Chill",
    description: "Creamy base meets tangy tropical pineapple. A frosty, sweet, island indulgence.",
    price: "199",
    image: coffeeImages.tropicalChill,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 30,
    name: "Blushing Berry",
    description:
      "Thick, velvety blend of ice cream and strawberries. A perfectly sweet, fruity, and nostalgic treat.",
    price: "199",
    image: coffeeImages.blushingBerry,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 31,
    name: "Tropical Sunshine",
    description:
      "The essence of tropical summer blended thick and smooth. Rich mango flavor in a creamy shake.",
    price: "199",
    image: coffeeImages.tropicalSunshine,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 32,
    name: "Crunchy Choco Delight (KitKat)",
    description: "Chocolate shake with real Kit Kat pieces. Creamy indulgence with a crunchy wafer break.",
    price: "229",
    image: coffeeImages.crunchyChocoDelight,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 33,
    name: "Cookie Crumble (Oreo)",
    description:
      "The ultimate cookies-and-cream. A thick, cold shake with chunks of crunchy chocolate wafer.",
    price: "229",
    image: coffeeImages.cookieCrumble,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 34,
    name: "Golden Nut Bliss (Ferrero)",
    description: "Velvety chocolate and hazelnut blend. A rich, cold treat with a satisfying nutty crunch.",
    price: "229",
    image: coffeeImages.goldenNutBliss,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 35,
    name: "Spiced Biscuit Bliss (Biscoff)",
    description: "Creamy shake with caramelized Biscoff spice. Thick, frosty, and loaded with cookie crunch.",
    price: "279",
    image: coffeeImages.spicedBiscuitBliss,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 36,
    name: "Choco Island Freak Shake",
    description:
      "Chocolate overload and dripping with sprinkles. The thick, dark shake with an Oreo and Kit Kat.",
    price: "249",
    image: coffeeImages.chocoIslandFreakShake,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },
  {
    id: 37,
    name: "Brownie Shake",
    description:
      "Decadent chocolate meets fudgy brownie chunks. A rich, frosty shake with a satisfying chew.",
    price: "229",
    image: coffeeImages.brownieShake,
    category: "Shakes",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
    variants: [],
    addOns: [
      { name: "Ice Cream", price: "₹30" },
      { name: "Whipped Cream", price: "₹30" },
    ],
  },

  // ============= Mojitos =================
  {
    id: 38,
    name: "Blueberry Mojito",
    description: "Crisp mint and zesty lime meet sweet, plump blueberries. Intensely cool and bubbly.",
    price: "189",
    image: coffeeImages.blueberry,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Minty", "Icy"],
    fit: "Contain",
  },
  {
    id: 39,
    name: "Cool Blue Mojito",
    description: "The classic mint and lime, electrified blue. Intensely cool, crisp, and ultra-bubbly.",
    price: "189",
    image: coffeeImages.coolBlue,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Minty", "Icy"],
    fit: "Contain",
  },
  {
    id: 40,
    name: "Green Apple Mojito",
    description: "Mint and lime with a tart green apple kick. Crisp, cool, and utterly fizzy refreshment.",
    price: "189",
    image: coffeeImages.greenApple,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 41,
    name: "Grenadine Mojito",
    description:
      "Classic zest and mint with a sweet grenadine burst. Perfectly cool, vibrant, and ultra-bubbly.",
    price: "189",
    image: coffeeImages.grenadine,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 42,
    name: "Litchi Mojito",
    description: "Mint and lime with sweet, exotic litchi. Fragrant, cool, and perfectly bubbly.",
    price: "189",
    image: coffeeImages.litchi,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },
  {
    id: 43,
    name: "Watermelon Mojito",
    description: "Invigorating mint and lime with a sweet watermelon burst. Perfectly cool, and refreshing.",
    price: "189",
    image: coffeeImages.watermelon,
    category: "Mojitos",
    rating: 4.8,
    time: "3 mins",
    tags: ["Thick", "Icy"],
    fit: "Contain",
  },

  // ============= Desserts =================
  {
    id: 44,
    name: "Biscoff Cheesecake",
    description:
      "Creamy base and irresistible caramelized Biscoff. A rich, velvety treat with a crunchy cookie crust.",
    price: "$4.00",
    image: coffeeImages.biscoffCake,
    category: "Desserts",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Crunchy"],
    fit: "Contain",
  },
  {
    id: 45,
    name: "Blueberry Cheesecake",
    description: "Velvety cream cheese and a buttery crust. Crowned with a burst of sweet, tart blueberries.",
    price: "$4.00",
    image: coffeeImages.blueberryCake,
    category: "Desserts",
    rating: 4.8,
    time: "3 mins",
    tags: ["Creamy", "Velvety"],
    fit: "Contain",
  },
  {
    id: 46,
    name: "Brownie",
    description:
      "Deep, dark chocolate baked to fudgy perfection. A rich, chewy, and utterly irresistible classic.",
    price: "$4.00",
    image: coffeeImages.brownie,
    category: "Desserts",
    rating: 4.8,
    time: "3 mins",
    tags: ["Chocolaty", "Fudgy"],
    fit: "Contain",
  },
  {
    id: 47,
    name: "New York Cheesecake",
    description: "The dense, ultra-rich classic set on a graham crust. Velvety smooth.",
    price: "$4.00",
    image: coffeeImages.newYorkCheesecake,
    category: "Desserts",
    rating: 4.9,
    time: "3 mins",
    tags: ["Smooth", "Velvety"],
    fit: "Contain",
  },
  {
    id: 48,
    name: "Sizzling",
    description:
      "The ultimate chocolate experience, sizzling. Fudgy brownie topped with melting ice cream and sauce.",
    price: "$4.00",
    image: coffeeImages.sizzling,
    category: "Desserts",
    rating: 4.9,
    time: "3 mins",
    tags: ["Smooth", "Velvety"],
    fit: "Contain",
  },
  {
    id: 49,
    name: "Green Tea",
    description: "Light and calming with antioxidants. It offers a calm, refreshing experience.",
    price: "169",
    image: coffeeImages.greenTea,
    category: "Hot Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
  },
  {
    id: 50,
    name: "Hot Chocolate",
    description: "",
    price: "169",
    image: coffeeImages.hotChocolate,
    category: "Hot Chocolate",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
    variants: [
      { name: "Cocoa", price: "₹189" },
      { name: "Hazelnut", price: "₹209" },
      { name: "Caramel", price: "₹209" },
      { name: "Strawberry", price: "₹209" },
    ],
  },
  {
    id: 51,
    name: "French Velvet",
    description: "Elegant French-style hot coffee.",
    price: "219",
    image: coffeeImages.frenchVelvet,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
  },
  {
    id: 52,
    name: "Tonic Water",
    description: "Blend of espresso and tonic water.",
    price: "239",
    image: coffeeImages.tonicWaterEspresso,
    category: "Speciality Coffee",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
  },
  {
    id: 51,
    name: "Grenadine Ice Tea",
    description: "Sweet red berry twist.",
    price: "239",
    image: coffeeImages.grenadineIcedTea,
    category: "Iced Tea",
    rating: 4.8,
    time: "3 mins",
    tags: ["Traditional", "Warm"],
    fit: "Contain",
  },
  // {
  //   id: 52,
  //   name: "Grenadine Ice Tea",
  //   description: "Light and calming with antioxidants. It offers a calm, refreshing experience.",
  //   price: "239",
  //   image: coffeeImages.grenadineIcedTea,
  //   category: "Iced Tea",
  //   rating: 4.8,
  //   time: "3 mins",
  //   tags: ["Traditional", "Warm"],
  //   fit: "Contain",
  // },

  // ============= Food Items =================
  //Appetizers
  {
    id: 53,
    name: "Golden Sticks",
    subtitle: "French Fries - Salted",
    description: "Crispy classic fries.",
    price: "199",
    image: foodImages.goldenSticks,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 54,
    name: "Mozarella Crunch Sticks",
    subtitle: "Mozarella Sticks",
    description: "Melty mozzarella encased in crispy coating.",
    price: "199",
    image: foodImages.mozarellaSticks,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 55,
    name: "Zesty Potato Pops",
    subtitle: "Chilli Garlic Shots",
    description: "Crispy potato pops with chili garlic flavor.",
    price: "199",
    image: foodImages.zestyPotatoPops,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 56,
    name: "Golden Crisps",
    subtitle: "Hash Brown",
    description: "Crispy potato patties.",
    price: "209",
    image: foodImages.goldenCrisps,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 57,
    name: "Toasted Delight",
    subtitle: "Garlic Bread",
    description: "Warm, buttery garlic bread.",
    price: "209",
    image: foodImages.toastedDelight,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 58,
    name: "Fiesta Crunch",
    subtitle: "Nachos & Salsa",
    description: "Crispy nachos with tangy salsa.",
    price: "209",
    image: foodImages.fiestaCrunch,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 59,
    name: "Golden Rings",
    subtitle: "Onino Rings",
    description: "Crispy fried onion rings.",
    price: "209",
    image: foodImages.goldenRings,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 60,
    name: "Golden Wedges",
    subtitle: "Potato Wedges",
    description: "Seasoned potato wedges fried to perfection.",
    price: "229",
    image: foodImages.goldenWedges,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 61,
    name: "Spicy Crunch",
    subtitle: "Peri Peri Fries",
    description: "Zesty Seasoned Fries.",
    price: "229",
    image: foodImages.spicyCrunch,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 62,
    name: "Cheesy Garlic Bliss",
    subtitle: "Garlic Bread With Cheese",
    description: "Garlic Bread top with cheese.",
    price: "229",
    image: foodImages.cheesyGarlicBliss,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 63,
    name: "Pancake",
    subtitle: "Strawberry/Chocolate",
    description: "Fluffy pancakes drizzled with your choice of strawberry or chocolate sauce..",
    price: "229",
    image: foodImages.pancake,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 64,
    name: "Melted Bliss",
    subtitle: "Cheesy Fries",
    description: "Fries topped with melted cheese.",
    price: "249",
    image: foodImages.meltedBliss,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 65,
    name: "Avocado Toast",
    subtitle: "",
    description: "Creamy smashed avocado on toasted bread, finished with herbs and olive oil.",
    price: "269",
    image: foodImages.avocadoToast,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 66,
    name: "Chicken Tikka",
    subtitle: "Garlic Bread",
    description: "Garlic bread topped with flavorful chicken tikka and melted cheese.",
    price: "239",
    image: foodImages.cheesyGarlicBliss,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 67,
    name: "Crispy Bites",
    subtitle: "Chicken Nuggets",
    description: "Golden, crunchy chicken bites.",
    price: "249",
    image: foodImages.crispyBites,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 68,
    name: "Chicken Wings",
    subtitle: "",
    description: "Crispy wings coated in spicy hot sauce.",
    price: "249",
    image: foodImages.chickenWings,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 69,
    name: "Chicken Popcorn",
    subtitle: "",
    description: "Bite-sized, crunchy chicken pieces with a hint of spice.",
    price: "249",
    image: foodImages.chickenPopcorn,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 70,
    name: "Chicken Cheesy Fries",
    subtitle: "",
    description: "Crispy fries loaded with cheese, sauce, and tender chicken bits.",
    price: "249",
    image: foodImages.chickenCheesyFries,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 71,
    name: "Chicken Tandoori Seekh Kebab",
    subtitle: "",
    description: "Savory minced chicken rolls cooked with Indian spices.",
    price: "249",
    image: foodImages.chickenTandooriSeekhKebab,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Appetizers"],
    fit: "Contain",
  },
  {
    id: 72,
    name: "Chicken Seekh Kebab",
    subtitle: "",
    description: "Minced chicken skewers grilled with aromatic spices.",
    price: "249",
    image: foodImages.chickenSeekhKebab,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Appetizers"],
    fit: "Contain",
  },

  // Sandwiches

  {
    id: 73,
    name: "Bombay Sandwich",
    subtitle: "",
    description: "Street-style sandwich with veggies & chutney.",
    price: "239",
    image: foodImages.vegCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 74,
    name: "Veg Cheese Sandwich",
    subtitle: "",
    description: "Grilled sandwich with melted cheese.",
    price: "239",
    image: foodImages.vegCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 75,
    name: "Mexican Corn",
    subtitle: "",
    description: "Creamy corn filling with mild spices.",
    price: "239",
    image: foodImages.vegCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 76,
    name: "Chocolate",
    subtitle: "",
    description: "Toasted bread filled with rich chocolate spread.",
    price: "239",
    image: foodImages.vegCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 77,
    name: "Paneer Tikka",
    subtitle: "",
    description: "Grilled paneer cubes with tangy tikka sauce.",
    price: "249",
    image: foodImages.vegCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 78,
    name: "Coleslaw",
    subtitle: "",
    description: "Creamy, crunchy coleslaw.",
    price: "279",
    image: foodImages.vegCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 79,
    name: "Veg Club",
    subtitle: "",
    description: "Triple-layered with fresh veggies",
    price: "279",
    image: foodImages.vegCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 80,
    name: "Egg Cheese",
    subtitle: "",
    description: "Soft egg omelette layered with cheese",
    price: "279",
    image: foodImages.eggCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 81,
    name: "Grilled Chicken",
    subtitle: "",
    description: "Juicy grilled chicken with fresh veggies.",
    price: "279",
    image: foodImages.eggCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 82,
    name: "Chicken Tikka",
    subtitle: "",
    description: "Spicy grilled chicken with tikka flavors",
    price: "279",
    image: foodImages.eggCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 83,
    name: "Chicken Sausage",
    subtitle: "",
    description: "Flavorful sausage filling.",
    price: "279",
    image: foodImages.eggCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 84,
    name: "Chicken Tandoor",
    subtitle: "",
    description: "Spiced tandoori chicken in soft bread.",
    price: "279",
    image: foodImages.eggCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Sandwiches"],
    fit: "Contain",
  },
  {
    id: 85,
    name: "Chicken Club",
    subtitle: "",
    description: "Triple-decker with chicken, lettuce & mayo.",
    price: "299",
    image: foodImages.eggCheeseSandwich,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Sandwiches"],
    fit: "Contain",
  },

  // Pastas
  {
    id: 86,
    name: "Creamy Alfredo",
    subtitle: "Penne Alfredo",
    description: "White sauce pasta, smooth and cheesy.",
    price: "349", // default (Veg)
    image: foodImages.creamyAlfredo, // add this in menuImages
    category: "Food",
    rating: 4.8,
    time: "8 mins",
    tags: ["Food", "Pastas"],
    variants: [
      { name: "Veg", price: "349" },
      { name: "Non-Veg", price: "369" },
    ],
  },
  {
    id: 87,
    name: "Spicy Arrabiata",
    subtitle: "Arrabiata Pasta",
    description: "Red sauce pasta with herbs and spice.",
    price: "349",
    image: foodImages.spicyArribiata,
    category: "Food",
    rating: 4.8,
    time: "8 mins",
    tags: ["Food", "Pastas"],
    variants: [
      { name: "Veg", price: "349" },
      { name: "Non-Veg", price: "369" },
    ],
  },
  {
    id: 88,
    name: "Cheesy Comfort",
    subtitle: "Mac n Cheese",
    description: "Baked macaroni in creamy cheese.",
    price: "349",
    image: foodImages.cheesyComfort,
    category: "Food",
    rating: 4.8,
    time: "8 mins",
    tags: ["Food", "Pastas"],
    variants: [
      { name: "Veg", price: "349" },
      { name: "Non-Veg", price: "369" },
    ],
  },
  {
    id: 89,
    name: "Garlic Herb Delight",
    subtitle: "Aglio Olio",
    description: "Simple garlic & chili olive oil pasta.",
    price: "349",
    image: foodImages.garlicHerbDelight,
    category: "Food",
    rating: 4.8,
    time: "8 mins",
    tags: ["Food", "Pastas"],
    variants: [
      { name: "Veg", price: "349" },
      { name: "Non-Veg", price: "369" },
    ],
  },
  {
    id: 90,
    name: "Rosy Bliss",
    subtitle: "Pink Sauce Pasta",
    description: "Blend of red & white sauce, creamy & tangy.",
    price: "349",
    image: foodImages.rosyBliss,
    category: "Food",
    rating: 4.8,
    time: "8 mins",
    tags: ["Food", "Pastas"],
    variants: [
      { name: "Veg", price: "349" },
      { name: "Non-Veg", price: "369" },
    ],
  },

  // Wraps
  {
    id: 91,
    name: "Paneer Wrap",
    subtitle: "",
    description: "Spiced paneer with salad & mayo.",
    price: "239",
    image: foodImages.paneerWrap,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Wraps"],
    fit: "Contain",
  },
  {
    id: 92,
    name: "Mexican Corn",
    subtitle: "",
    description: "Spiced corn, veggies, and tangy dressing.",
    price: "239",
    image: foodImages.mexicanCorn,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Wraps"],
    fit: "Contain",
  },
  {
    id: 93,
    name: "Veg Cheese",
    subtitle: "",
    description: "Grilled veggies with melted cheese.",
    price: "239",
    image: foodImages.vegCheese,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Wraps"],
    fit: "Contain",
  },
  {
    id: 94,
    name: "Chicken Cheese",
    subtitle: "",
    description: "Chicken and cheese wrapped in soft tortilla.",
    price: "249",
    image: foodImages.chickenCheese,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Wraps"],
    fit: "Contain",
  },
  {
    id: 95,
    name: "Peri Peri Chicken",
    subtitle: "",
    description: "Spicy peri-peri chicken with crisp veggies.",
    price: "249",
    image: foodImages.periPeriChicken,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Wraps"],
    fit: "Contain",
  },
  {
    id: 96,
    name: "Chicken Sausage",
    subtitle: "",
    description: "Chicken sausage with veggies and sauces",
    price: "249",
    image: foodImages.chickenSausage,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Wraps"],
    fit: "Contain",
  },
  {
    id: 97,
    name: "Tandoori Chicken",
    subtitle: "",
    description: " Indian-style spicy chicken wrap.",
    price: "249",
    image: foodImages.tandooriChicken,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Wraps"],
    fit: "Contain",
  },

  // Croissants
  {
    id: 98,
    name: "Paneer Tikka Croissant",
    subtitle: "",
    description: "Flaky croissant stuffed with smoky paneer tikka and sauces.",
    price: "249",
    image: foodImages.vegCroissant,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Sandwich Croissant"],
    fit: "Contain",
  },
  {
    id: 99,
    name: "Veggie Croissant",
    subtitle: "",
    description: "Fresh veggies and cheese tucked into a warm, flaky croissant.",
    price: "249",
    image: foodImages.vegCroissant,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Sandwich Croissant"],
    fit: "Contain",
  },
  {
    id: 100,
    name: "Avocado Croissant",
    subtitle: "",
    description: "Buttery croissant layered with creamy avocado and herbs.",
    price: "249",
    image: foodImages.vegCroissant,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Veg", "Sandwich Croissant"],
    fit: "Contain",
  },
  {
    id: 101,
    name: "Chicken Tikka Croissant",
    subtitle: "",
    description: "Tender chicken tikka wrapped in a buttery croissant.",
    price: "279",
    image: foodImages.nonVegCroissant,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Sandwich Croissant"],
    fit: "Contain",
  },
  {
    id: 102,
    name: "Peri Peri Chicken Croissant",
    subtitle: "",
    description: "Spicy peri peri chicken with cheese and sauce in a golden croissant.",
    price: "279",
    image: foodImages.nonVegCroissant,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Sandwich Croissant"],
    fit: "Contain",
  },
  {
    id: 103,
    name: "Chicken Sausage Croissant",
    subtitle: "",
    description: "Savory chicken sausage paired with cheese and mustard in a flaky crust.",
    price: "279",
    image: foodImages.nonVegCroissant,
    category: "Food",
    rating: 4.8,
    time: "3 mins",
    tags: ["Non-Veg", "Sandwich Croissant"],
    fit: "Contain",
  },
  // Pizzas
  {
    id: 104,
    name: "Margherita",
    subtitle: "",
    description: "Classic cheese & tomato.",
    price: "249",
    image: foodImages.margherita,
    category: "Food",
    rating: 4.8,
    time: "12 mins",
    tags: ["Veg", "Pizzas"],
    fit: "Contain",
  },
  {
    id: 105,
    name: "Corn & Cheese",
    subtitle: "",
    description: "Sweet corn with gooey cheese.",
    price: "249",
    image: foodImages.cornAndCheese,
    category: "Food",
    rating: 4.8,
    time: "12 mins",
    tags: ["Veg", "Pizzas"],
    fit: "Contain",
  },
  {
    id: 106,
    name: "Veggie",
    subtitle: "",
    description: "Fresh seasonal veggies.",
    price: "279",
    image: foodImages.veggie,
    category: "Food",
    rating: 4.8,
    time: "12 mins",
    tags: ["Veg", "Pizzas"],
    fit: "Contain",
  },
  {
    id: 107,
    name: "Spiced Paneer",
    subtitle: "",
    description: "Tandoori paneer with spices.",
    price: "279",
    image: foodImages.spicedPaneer,
    category: "Food",
    rating: 4.8,
    time: "12 mins",
    tags: ["Veg", "Pizzas"],
    fit: "Contain",
  },
  {
    id: 108,
    name: "Paneer Makhani",
    subtitle: "",
    description: "Spiced paneer, rich makhani sauce, and mozzarella.",
    price: "279",
    image: foodImages.paneerMakhani,
    category: "Food",
    rating: 4.8,
    time: "12 mins",
    tags: ["Veg", "Pizzas"],
    fit: "Contain",
  },
  {
    id: 109,
    name: "Mushroom",
    subtitle: "",
    description: "Mushrooms, herbs & mozzarella.",
    price: "279",
    image: foodImages.mushroom,
    category: "Food",
    rating: 4.8,
    time: "12 mins",
    tags: ["Veg", "Pizzas"],
    fit: "Contain",
  },
  {
    id: 110,
    name: "Schezwan Margherita",
    subtitle: "",
    description: "Spicy Indo-Chinese twist.",
    price: "279",
    image: foodImages.schezwan,
    category: "Food",
    rating: 4.8,
    time: "12 mins",
    tags: ["Veg", "Pizzas"],
    fit: "Contain",
  },
  {
    id: 111,
    name: "Chicken Sausage",
    subtitle: "",
    description: "Topped with juicy sausages.",
    price: "279",
    image: foodImages.chickenSausagePizza,
    category: "Food",
    rating: 4.8,
    time: "12 mins",
    tags: ["Non-Veg", "Pizzas"],
    fit: "Contain",
  },
  {
    id: 112,
    name: "Chicken Pepperoni",
    subtitle: "",
    description: "Classic pepperoni-style chicken.",
    price: "349",
    image: foodImages.chickenPepperoni,
    category: "Food",
    rating: 4.8,
    time: "13 mins",
    tags: ["Non-Veg", "Pizzas"],
    fit: "Contain",
  },
  {
    id: 113,
    name: "Chicken Tikka",
    subtitle: "",
    description: "Grilled tikka chicken & cheese.",
    price: "349",
    image: foodImages.chiceknTikka,
    category: "Food",
    rating: 4.8,
    time: "13 mins",
    tags: ["Non-Veg", "Pizzas"],
    fit: "Contain",
  },
  {
    id: 114,
    name: "Pepper BBQ & Onion",
    subtitle: "",
    description: "BBQ chicken with caramelized onions.",
    price: "349",
    image: foodImages.pepperBBQOnion,
    category: "Food",
    rating: 4.8,
    time: "13 mins",
    tags: ["Non-Veg", "Pizzas"],
    fit: "Contain",
  },
  {
    id: 115,
    name: "Peri Peri Chicken",
    subtitle: "",
    description: "Zesty peri peri chicken with gooey cheese.",
    price: "379",
    image: foodImages.periPeriChickenPizza,
    category: "Food",
    rating: 4.8,
    time: "13 mins",
    tags: ["Non-Veg", "Pizzas"],
    fit: "Contain",
  },
  // Breaksfast
  {
    id: 116,
    name: "Masala Maggie",
    subtitle: "",
    description: "Classic Indian Maggi noodles tossed with flavorful spices and fresh veggies.",
    price: "189",
    image: foodImages.masalaMaggie,
    category: "Breakfast",
    rating: 4.8,
    time: "8 mins",
    tags: [""],
    fit: "Contain",
  },
  {
    id: 117,
    name: "Spiced Delight",
    subtitle: "Masala Omelette",
    description:
      "Fluffy omelette packed with onions, tomatoes, and Indian spices, served alongside hash brown and sautéed veggies.",
    price: "299",
    image: foodImages.spicedDelight,
    category: "Breakfast",
    rating: 4.8,
    time: "10 mins",
    tags: [""],
    fit: "Contain",
  },
  {
    id: 118,
    name: "Savory Fungi",
    subtitle: "Mushroom Omelette",
    description:
      "Omelette loaded with sautéed mushrooms and herbs, paired with crispy hash brown and fresh veggies.",
    price: "299",
    image: foodImages.savoryFungi,
    category: "Breakfast",
    rating: 4.8,
    time: "10 mins",
    tags: [""],
    fit: "Contain",
  },
  {
    id: 119,
    name: "Creamy Scramble",
    subtitle: "Scrambled Egg",
    description:
      "Soft scrambled eggs cooked to fluffy perfection, served with golden hash brown and sautéed veggies.",
    price: "299",
    image: foodImages.creamyScrambled,
    category: "Breakfast",
    rating: 4.8,
    time: "10 mins",
    tags: [""],
    fit: "Contain",
  },
  {
    id: 120,
    name: "Hispanic Charm",
    subtitle: "Spanish Omelette",
    description:
      "Spanish-style omelette with crispy hash brown, fresh veggies, and light seasoning, accompanied by herb brown and sautéed veggies.",
    price: "299",
    image: foodImages.hispanicCharm,
    category: "Breakfast",
    rating: 4.8,
    time: "10 mins",
    tags: [""],
    fit: "Contain",
  },
  {
    id: 121,
    name: "Golden Sunrise",
    subtitle: "Sunny Side Up",
    description:
      "Classic fried eggs with a perfectly runny yolk, served with crispy hash brown and sautéed veggies.",
    price: "299",
    image: foodImages.goldenSunrise,
    category: "Breakfast",
    rating: 4.8,
    time: "9 mins",
    tags: [""],
    fit: "Contain",
  },
  {
    id: 122,
    name: "Caesar Salad",
    subtitle: "(Veg)",
    description: "Crisp lettuce tossed with creamy Caesar dressing, parmesan, and crunchy croutons.",
    price: "299",
    image: foodImages.caesarSaladVeg,
    category: "Breakfast",
    rating: 4.8,
    time: "6 mins",
    tags: [""],
    fit: "Contain",
  },
  {
    id: 123,
    name: "Caesar Salad",
    subtitle: "(Non-Veg)",
    description: "Classic Caesar salad topped with juicy grilled chicken for a hearty start to your day.",
    price: "299",
    image: foodImages.caesarSaladNv,
    category: "Breakfast",
    rating: 4.8,
    time: "7 mins",
    tags: [""],
    fit: "Contain",
  },
  // ============= Burgers (id: 124 - 129) =================
  {
    id: 124,
    name: "Veg Burger",
    subtitle: "",
    description: "Crispy veggie patty with lettuce & sauces.",
    price: "219",
    image: foodImages.vegBurger,
    category: "Food",
    rating: 4.8,
    time: "10 mins",
    tags: ["Burgers", "Veg"],
    fit: "Contain",
  },
  {
    id: 125,
    name: "Paneer Burger",
    subtitle: "",
    description: "Grilled paneer with spiced mayo.",
    price: "229",
    image: foodImages.paneerBurger,
    category: "Food",
    rating: 4.8,
    time: "10 mins",
    tags: ["Burgers", "Veg"],
    fit: "Contain",
  },
  {
    id: 126,
    name: "Maharaja Veg",
    subtitle: "",
    description: "Double patty loaded with cheese & flavor.",
    price: "249",
    image: foodImages.maharajaVeg,
    category: "Food",
    rating: 4.8,
    time: "11 mins",
    tags: ["Burgers", "Veg"],
    fit: "Contain",
  },
  {
    id: 127,
    name: "Chicken Cheese",
    subtitle: "",
    description: "Juicy chicken patty with melted cheese.",
    price: "249",
    image: foodImages.chickenCheeseBurger,
    category: "Food",
    rating: 4.8,
    time: "11 mins",
    tags: ["Burgers", "Non-Veg"],
    fit: "Contain",
  },
  {
    id: 128,
    name: "Tandoori Chicken",
    subtitle: "",
    description: "Spicy grilled chicken with smoky flavor.",
    price: "249",
    image: foodImages.tandooriChickenBurger,
    category: "Food",
    rating: 4.8,
    time: "11 mins",
    tags: ["Burgers", "Non-Veg"],
    fit: "Contain",
  },
  {
    id: 129,
    name: "Maharaja Non-Veg",
    subtitle: "",
    description: "Double chicken patty with rich sauces.",
    price: "279",
    image: foodImages.maharajaNonVeg,
    category: "Food",
    rating: 4.8,
    time: "12 mins",
    tags: ["Burgers", "Non-Veg"],
    fit: "Contain",
  },
];
